### ISSUE TITLE
Occur https://api.heygen.com/v1/streaming.new 401 Unauthorized, when use trial token

### ISSUE THREAD

**Issue by gaozhou** [HeyGen-Official/InteractiveAvatarNextJSDemo#5]

**Comment by chpio** [comment]
i've got a response for "https://api.heygen.com/v1/streaming.create_token" saying

> {"detail":"Unsupported media type '' in request. 'application/json' is required."}

So i've set the `"content-type": "application/json"` header and set body to an empty json: `body: JSON.stringify({})`, which seem to have fixed the issue.

**Comment by billStatham** [comment]
> > Hi guys I am also facing the same problem.
> > I saw a timeout in the log in the console. I initially judged that this was related to the use in my region. I can access the HeyGen website through VPN in mainland China, but calling the API times out.
> > log :
> > ✓ Starting...
> > ✓ Ready in 1695ms
> > ○ Compiling / ...
> > ✓ Compiled / in 4.4s
> > GET / 200 in 4990ms
> > ✓ Compiled /api/get-access-token in 137ms
> > Error retrieving access token: TypeError: fetch failed
> > at node:internal/deps/undici/undici:12502:13
> > at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> > at async POST (F:\OpenSource\InteractiveAvatarNextJSDemo.next\server\chunks\app_api_get-access-token_route_ts_b6d0fc._.js:15:21)
> > at async F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55038
> > at async ek.execute (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:45808)
> > at async ek.handle (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:56292)
> > at async doRender (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\base-server.js:1377:42)
> > at async cacheEntry.responseCache.get.routeKind (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\base-server.js:1599:28)
> > at async DevServer.renderToResponseWithComponentsImpl (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\base-server.js:1507:28)
> > at async DevServer.renderPageComponent (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\base-server.js:1931:24)
> > at async DevServer.renderToResponseImpl (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\base-server.js:1969:32)
> > at async DevServer.pipeImpl (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\base-server.js:920:25)
> > at async NextNodeServer.handleCatchallRenderRequest (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\next-server.js:272:17)
> > at async DevServer.handleRequestImpl (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\base-server.js:816:17)
> > at async F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\dev\next-dev-server.js:339:20
> > at async Span.traceAsyncFn (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\trace\trace.js:154:20)
> > at async DevServer.handleRequest (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
> > at async invokeRender (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\lib\router-server.js:174:21)
> > at async handleRequest (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\lib\router-server.js:353:24)
> > at async requestHandlerImpl (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\lib\router-server.js:377:13)
> > at async Server.requestListener (F:\OpenSource\InteractiveAvatarNextJSDemo\node_modules\next\dist\server\lib\start-server.js:141:13) {
> > [cause]: ConnectTimeoutError: Connect Timeout Error
> > at onConnectTimeout (node:internal/deps/undici/undici:6635:28)
> > at node:internal/deps/undici/undici:6587:50
> > at Immediate._onImmediate (node:internal/deps/undici/undici:6617:37)
> > at process.processImmediate (node:internal/timers:478:21)
> > at process.callbackTrampoline (node:internal/async_hooks:130:17) {
> > code: 'UND_ERR_CONNECT_TIMEOUT'
> > }
> > }
> 
> same problem，did you solve it ?

same here.
